### ISSUE TITLE
Compiling fails because modules cannot be downloaded

### ISSUE THREAD

**Issue by graphik55** [Email-Analysis-Toolkit/command-injection-scanner#1]
### Steps to reproduce:
- follow the installation steps of the readme
- the make command will fail because it is unable to download the modules "github.com/zmap/zgrab2/modules/smtp_session_fixation" and "github.com/zmap/zgrab2/modules/smtp_cross_protocol"

### Expected behavior:
The make command finishes successfully.

### Solution:
Those modules should be provided in this repository too or the lines should be commented out or removed from "modules/starttls_research.go".

### Workaround:
Before running the make command commented out or remove the two modules from "modules/starttls_research.go".

**Comment by duesee** [comment]
Thank you @graphik55 for the report and @DvDOOM for the fix! :+1:
